### ISSUE TITLE
BasePlugin.js - Critical dependency warning in webpack

### ISSUE THREAD

**Issue by bradfrosty** [lightstep/opentelemetry-exporter-js#12]
I'm trying to setup `lightstep-opentelemetry-exporter` and while building I'm getting a warning in webpack. 

```
WARNING in ./node_modules/lightstep-opentelemetry-exporter/node_modules/@opentelemetry/core/build/src/trace/instrumentation/BasePlugin.js 77:46-103
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/lightstep-opentelemetry-exporter/node_modules/@opentelemetry/core/build/src/index.js
 @ ./node_modules/lightstep-opentelemetry-exporter/build/src/transform.js
 @ ./node_modules/lightstep-opentelemetry-exporter/build/src/create-report-request-fn.js
 @ ./node_modules/lightstep-opentelemetry-exporter/build/src/exporter.js
 @ ./node_modules/lightstep-opentelemetry-exporter/build/src/index.js
 @ ./lightstep/bootstrap.ts
```

There's a related issue that was closed in the `opentelemetry-js` repo: https://github.com/open-telemetry/opentelemetry-js/issues/814

Seems like this may only be an issue for browser users and that it could possibly be fixed with a dependency update.

**Comment by hongbo-miao** [comment]
Got same warning when add `lightstep-opentelemetry-exporter` to an app created by create-react-app.

> ./node_modules/lightstep-opentelemetry-exporter/node_modules/@opentelemetry/core/build/src/trace/instrumentation/BasePlugin.js
> Critical dependency: the request of a dependency is an expression

**Comment by andrewhsu** [comment]
closing issue because this repo is now archived
